

386_OBJECTS=\
 $(OBJ_PATH)\$O\fuseinit.obj \
 $(OBJ_PATH)\$O\fuseio.obj \
 $(OBJ_PATH)\$O\hashmap.obj \
 $(OBJ_PATH)\$O\fusequery.obj \


_RES_FILE=$(OBJ_PATH)\$O\fuse.res



# lowercased
BASEDIR=d:\winddk\7600.16385.1
OBJECT_ROOT=d:\winddk\7600.16385.1
MAKEDIR_LOWERCASE=d:\workspace\ifs\fuse\wxp
OBJ_PATH=d:\workspace\ifs\fuse\wxp
CONCURRENT_MIDL=0
CONCURRENT_MANIFEST_BUILD=0
